In [1]:
import torch
from torch import nn

In [2]:
#100개의 채널을 가진 5가지 개체
x=torch.randn(100,3)
layer=nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[-0.1418, -0.0659,  0.3455],
        [ 0.4105,  0.2257, -0.2562],
        [-0.1458,  0.0124,  0.0587],
        [ 0.5671,  0.1878, -0.3392],
        [-0.0637, -0.1989, -0.3858]], requires_grad=True)
Parameter containing:
tensor([ 0.3506, -0.5677, -0.1909, -0.2864, -0.1271], requires_grad=True)


In [3]:
x=torch.randn(2,5)
layer=nn.ReLU()
print(layer(x))

tensor([[1.0860, 0.4611, 0.8871, 0.7430, 0.5820],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


In [4]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.3) # p는 죽일 확률
print(drop(x))

tensor([[-2.7537, -2.3018,  0.0000,  0.2028,  0.4468, -2.7768,  0.0000],
        [ 0.0000, -0.3012, -0.0155,  0.0000,  0.6316,  0.1460,  2.8386],
        [ 0.0000,  0.1647,  0.5856,  0.3073, -0.3371, -0.1490, -0.0000]])


In [5]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))

    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode

tensor([[ 1.6551,  1.3304,  0.9100,  0.0000,  0.0000, -1.0969, -0.5741],
        [ 0.6276,  0.4048,  0.2331, -0.1081,  0.2521,  0.2078, -0.0000],
        [ 0.7395,  0.0000,  0.0000, -0.0000,  0.0000, -0.1985, -0.0421]],
       grad_fn=<MulBackward0>)
tensor([[ 1.1586,  0.9313,  0.6370,  0.0560,  0.8945, -0.7678, -0.4019],
        [ 0.4393,  0.2834,  0.1632, -0.0756,  0.1765,  0.1455, -0.0403],
        [ 0.5177,  0.4536,  0.7551, -0.1101,  0.2295, -0.1390, -0.0295]],
       grad_fn=<AddmmBackward0>)


In [6]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape #5*5사이즈 흑백 사진이 32장 있음
# nn.Linear(3,5) # 채채 # 얘는 채 또는 개채를 원함, 개 x 3
# nn.Conv2d(3,5) # 채채 # 얘는 채행열 또는 개채행열을 원함, 개 x 3 x 행 x 열

torch.Size([32, 2, 5, 5])

In [8]:
layer = nn.Conv2d(3,5,3, stride=2, padding=1) # weight의 shape은?
print(layer(torch.randn(32,3,5,5)).shape) #in-chanell이 3이니까
print(layer.weight.shape)

torch.Size([32, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [9]:
conv1 = nn.Conv2d(1,8,6,stride=2) #필터 8개, 커널 크기: 6X6, 스트라이드:2
x=torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2 = nn.Conv2d(8,16,3,padding=1) #필터 16개, 커널 크기: 3X3
print(conv2(conv1(x)).shape)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=(2,2)) # 필터의 개수는 유지, 넓은 범위를 대표하는 하나의 값 뽑음
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [10]:
maxpool = nn.MaxPool2d(4) # 2 로만 줘도 자동 kernel_size=2, stride=(2,2)
x=torch.randn(1,1,8,8)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,8,8)).shape)

tensor([[[[ 0.9890, -0.6600, -0.1028,  0.0874,  0.3653,  0.1342, -1.1926,
            0.8078],
          [ 1.2284, -0.3924, -1.0044, -1.0658,  1.1088, -1.0075,  0.3217,
            0.8711],
          [-0.6463,  0.0506,  0.2405,  1.3239,  0.2782, -1.5496,  1.5206,
           -0.0054],
          [ 0.6592, -0.1167,  0.1732,  1.0022,  0.8596,  1.8834, -1.4530,
           -0.5550],
          [ 1.4623, -0.8171, -0.5139, -0.5193, -0.6091, -0.8953, -1.9551,
           -0.9878],
          [-0.1200, -1.8639, -1.5772,  0.7093, -0.8237, -0.7821,  0.7939,
            1.2412],
          [ 2.8970,  0.2114, -0.1639,  1.1875,  0.9742,  0.0625, -0.7923,
           -0.0507],
          [-1.3962,  0.3059,  0.4347, -1.0394, -0.0532, -0.1185,  0.7085,
           -0.6566]]]])
tensor([[[[1.3239, 1.8834],
          [2.8970, 1.2412]]]])
torch.Size([32, 3, 2, 2])


In [11]:
avgpool=nn.AvgPool2d(2) #평균으로 대체
x=torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[-0.1932,  1.3493,  0.5854,  1.2127,  0.0536, -0.6936],
          [ 1.6991, -0.2525, -0.6257, -0.3006,  1.6222,  0.0743],
          [-0.7531, -1.0564, -1.6996, -0.7161, -0.1723,  0.0786],
          [ 0.7234, -0.4088, -1.3891, -0.2129, -0.0422, -0.2871],
          [-0.2752, -0.8385,  2.0286,  0.7986,  0.4103, -0.0733],
          [-0.9675, -0.0100,  1.1494, -1.8286,  0.0231, -1.0290]]]])
tensor([[[[ 0.6507,  0.2180,  0.2641],
          [-0.3737, -1.0044, -0.1057],
          [-0.5228,  0.5370, -0.1672]]]])
torch.Size([32, 3, 3, 3])


In [12]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2) # 1채널->8채널, 커널크기 6, 스트라이드 2
        self.conv2 = nn.Conv2d(8,16,3,padding=1) # 8채널->16채널, 커널크기 3, 패딩 1
        self.Maxpool2 = nn.MaxPool2d(2) #커널 2, 스트라이드 2
        self.fc = nn.Linear(16*6*6,10) # MNIST는 10개의 클래스 분류 문제이니 10개로 출력,
        #feature map이 16, 6, 6임

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        # x = torch.flatten(x, start_dim=1)
        # x = self.fc(x)
        return x

x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape)

torch.Size([32, 16, 6, 6])


In [ ]:
"""
self.conv1 = nn.Sequential(
  nn.Conv2d(3, 8, 3, padding=1), # 3 -> 8 채널, 출력 크기 유지
  nn.BatchNorm2d(8)
  nn.ReLU()
)
self.Maxpool1 = nn.MaxPool2d(2)

self.conv2 = nn.Sequential(
  nn.Conv2d(8, 16, 3, padding=1),
  nn.BatchNorm2d(16)
  nn.ReLU()
)
self.Maxpool2 = nn.MaxPool2d(2)

self.conv3 = nn.Sequential(
  nn.Conv2d(16, 32, 3, padding=1),
  nn.BatchNorm2d(32)
  nn.ReLU()
)
self.Maxpool3 = nn.MaxPool2d(2)
"""
# Pooling은 해상도를 줄인다, 이를 보완하기 위해 채널 수를 늘려 정보량을 보존함.
# 초기에는 적은 채널로 시작해서, 뒤로 2배씩 채널을 증가시키는 것이 연산 효율 + 성능 면에서 나

## .parameters() vs .modules() vs .children() 그리고 isinstance의 활용

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x

model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [ ]:
model.parameters()

<generator object Module.parameters at 0x7f141bb95f90>

In [ ]:
list(model.parameters())[0]
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[-0.0134, -0.2526],
        [-0.6953,  0.6233],
        [-0.0113,  0.6361]], requires_grad=True)

In [ ]:
# for tranfer learning
model=MLP()
print([p for p in model.parameters() if p.requires_grad])

for p in model.parameters(): # 전체 freeze
    p.requires_grad=False
model.fc_out = nn.Linear(4,10)

params = [p for p in model.parameters() if p.requires_grad]
print(params)

from torch import optim
optimizer = optim.Adam(params, lr=0.1)

[Parameter containing:
tensor([[ 0.1996,  0.1994],
        [ 0.3444, -0.4502],
        [ 0.4380, -0.6523]], requires_grad=True), Parameter containing:
tensor([-0.5272,  0.6027, -0.4804], requires_grad=True), Parameter containing:
tensor([[ 0.4240, -0.4905, -0.5493],
        [ 0.4089, -0.3101, -0.2805],
        [ 0.1004,  0.1807, -0.1730],
        [-0.0322,  0.5067, -0.2101]], requires_grad=True), Parameter containing:
tensor([-0.2618,  0.3359, -0.0152, -0.5487], requires_grad=True), Parameter containing:
tensor([[-0.4201,  0.2369, -0.3969, -0.3237]], requires_grad=True), Parameter containing:
tensor([0.4398], requires_grad=True)]
[Parameter containing:
tensor([[-0.3634,  0.3684, -0.3112, -0.0318],
        [ 0.1439, -0.1164,  0.4683, -0.0255],
        [-0.0229, -0.4852,  0.4611, -0.3768],
        [ 0.2551, -0.3565,  0.4436, -0.1739],
        [ 0.1431, -0.4204, -0.1562,  0.1049],
        [ 0.3607,  0.1683, -0.1850,  0.4222],
        [ 0.4475,  0.0755, -0.4214, -0.0474],
        [ 0.0622,

In [ ]:
list(model.named_parameters())[0]
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]

('fc1.0.weight', Parameter containing:
 tensor([[ 0.1996,  0.1994],
         [ 0.3444, -0.4502],
         [ 0.4380, -0.6523]]))

In [ ]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[ 0.1996,  0.1994],
        [ 0.3444, -0.4502],
        [ 0.4380, -0.6523]])
fc1.0.bias
Parameter containing:
tensor([-0.5272,  0.6027, -0.4804])
fc2.0.weight
Parameter containing:
tensor([[ 0.4240, -0.4905, -0.5493],
        [ 0.4089, -0.3101, -0.2805],
        [ 0.1004,  0.1807, -0.1730],
        [-0.0322,  0.5067, -0.2101]])
fc2.0.bias
Parameter containing:
tensor([-0.2618,  0.3359, -0.0152, -0.5487])
fc_out.weight
Parameter containing:
tensor([[-0.3634,  0.3684, -0.3112, -0.0318],
        [ 0.1439, -0.1164,  0.4683, -0.0255],
        [-0.0229, -0.4852,  0.4611, -0.3768],
        [ 0.2551, -0.3565,  0.4436, -0.1739],
        [ 0.1431, -0.4204, -0.1562,  0.1049],
        [ 0.3607,  0.1683, -0.1850,  0.4222],
        [ 0.4475,  0.0755, -0.4214, -0.0474],
        [ 0.0622, -0.1349, -0.1851,  0.2030],
        [ 0.3657,  0.3324, -0.2247,  0.2239],
        [-0.0134, -0.4485, -0.1851, -0.4764]], requires_grad=True)
fc_out.bias
Parameter containing

In [ ]:
model.modules()

<generator object Module.modules at 0x7f141b78bdd0>

In [ ]:
list(model.modules())

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ), Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Linear(in_features=2, out_features=3, bias=True), ReLU(), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=3, out_features=4, bias=True), ReLU(), Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
print([m for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[ 0.1996,  0.1994],
        [ 0.3444, -0.4502],
        [ 0.4380, -0.6523]]), Parameter containing:
tensor([[ 0.4240, -0.4905, -0.5493],
        [ 0.4089, -0.3101, -0.2805],
        [ 0.1004,  0.1807, -0.1730],
        [-0.0322,  0.5067, -0.2101]]), Parameter containing:
tensor([[-0.3634,  0.3684, -0.3112, -0.0318],
        [ 0.1439, -0.1164,  0.4683, -0.0255],
        [-0.0229, -0.4852,  0.4611, -0.3768],
        [ 0.2551, -0.3565,  0.4436, -0.1739],
        [ 0.1431, -0.4204, -0.1562,  0.1049],
        [ 0.3607,  0.1683, -0.1850,  0.4222],
        [ 0.4475,  0.0755, -0.4214, -0.0474],
        [ 0.0622, -0.1349, -0.1851,  0.2030],
        [ 0.3657,  0.3324, -0.2247,  0.2239],
        [-0.0134, -0.4485, -0.1851, -0.4764]], requires_grad=True)]
[None, None, None]


In [ ]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)
        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[ 0.8947, -1.2693],
        [ 0.5346,  1.6689],
        [-0.0714,  1.6138]]), Parameter containing:
tensor([[-0.2995,  0.8541,  0.0983],
        [ 1.1411,  0.8850,  1.8759],
        [-0.3607, -0.4720,  0.0356],
        [-0.9508, -1.0568, -0.1150]]), Parameter containing:
tensor([[ 1.0350, -0.1308,  0.3618,  0.8463],
        [-1.0730,  0.9058, -0.5026, -0.4163],
        [ 0.1431,  0.7085, -0.4777,  0.3908],
        [ 0.2633,  0.0488, -0.0305, -0.0534],
        [-0.3727,  0.8493, -0.8423, -0.4329],
        [ 0.0821,  1.9561,  0.3025, -1.2846],
        [-0.1071, -1.0848,  0.5324,  1.6751],
        [-0.4850,  0.6923,  1.1755, -0.3045],
        [-0.3548, -0.0378,  1.3580,  0.5613],
        [ 1.5403,  0.2447,  2.2214,  0.1515]], requires_grad=True)]


In [ ]:
model.children()

<generator object Module.children at 0x7f141b78bf90>

In [ ]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
x = torch.randn(2,2)
list(model.children())[0](x)

tensor([[0.0000, 0.6386, 0.0000],
        [0.0000, 0.7796, 0.0000]])

In [ ]:
print(*list(model.children())[:2])
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
print(sub_network(x))

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
) Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)
tensor([[0.2836, 0.9011, 0.0000, 0.0000],
        [0.4041, 1.0259, 0.0000, 0.0000]])


## ModuleList vs Sequential

In [ ]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error!
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
tensor([[ 0.5768,  0.6888, -0.4326]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5768,  0.6888, -0.4326]], grad_fn=<AddmmBackward0>)


In [ ]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))

print(model) # 그냥 리스트로 하면 등록이 안돼있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다!

tensor([[ 0.8610, -0.0682, -0.5883]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Linear(in_features=3, out_features=3, bias=True)
  )
)


In [ ]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block)
print(model)
# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)

small_block(
  (block_x): Linear(in_features=1, out_features=1, bias=True)
  (block_y): Linear(in_features=1, out_features=1, bias=True)
)
Sequential(
  (0): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
  (1): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([-0.0330], grad_fn=<AddBackward0>) tensor([0.4277], grad_fn=<AddBackward0>)
